# Generated by Django 2.1.5 on 2019-03-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myticker', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockticker', models.CharField(max_length=10)),
                ('lasttradeday', models.CharField(max_length=10)),
                ('lastprice', models.CharField(max_length=10)),
                ('dailypnl', models.CharField(max_length=10)),
                ('mtdpnl', models.CharField(max_length=10)),
                ('ytdpnl', models.CharField(max_length=10)),
            ],
        ),
    ]
